### ISSUE TITLE
Inventory sructure

### ISSUE THREAD

**Issue by ShaAli** [Laurentius912/AriGato-Software#3]

**Comment by SpikeSpi3gel** [comment]
Having a simple ArrayList of items would work.

**Comment by ShaAli** [comment]
Yes, but I think it would be more efficient if we had a more organized structure.
A more organized structure would make displaying he contents of inventory much easier.

**Comment by ShaAli** [comment]
To make an array of ArrayList, you have to compile with -Xlint:unchecked and apparently it is bad design.

**Comment by ShaAli** [comment]
I guess if a 2D ArrayList is too complicated, we could use a single array.

**Comment by ShaAli** [comment]
The 2D ArrayList implementation works!!
